export const GET_GIF_DATA = 'GET_GIF_DATA';
export const UPDATE_GIF_DATA = 'UPDATE_GIF_DATA';
export const GET_GIF_DATA_LOADING = 'GET_GIF_DATA_LOADING';
export const GET_GIF_DATA_FETCHED = 'GET_GIF_DATA_FETCHED';

export const SET_LIST_VIEWABLE_ID = 'SET_LIST_VIEWABLE_ID';